version: '3.8'

services:
  app:
    image: ozbayhilmi/note-app:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/noteapp
    depends_on:
      - mongodb
    networks:
      - note-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - note-network

networks:
  note-network:
    driver: bridge

volumes:
  mongodb_data: 